version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000" # Map container port 8000 to host port 80
    environment:
      - MONGO_URI=mongodb://mongo:27017/your_database
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
